name: Auto Run Colab

on:
  schedule:
    - cron: '0 */6 * * *'   # 每6小时运行一次
  workflow_dispatch:

jobs:
  run_colab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Colab
        run: |
          curl -s -X POST "https://colab.research.google.com/github/mavin521/colab/blob/main/colab_streamer.ipynb"
